; PlatformIO - Desktop Companion PM
; Board: Arduino Uno (ATmega328P, 16MHz)
; Framework: arduino (necesar pentru upload simplu)
; Codul hardware e scris direct pe registri, fara functii Arduino

[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 9600
